export const SET_LOADING_TRUE = "SET_LOADING_TRUE";

export const GET_FEE_RATE_SUCCESS = "GET_FEE_RATE_SUCCESS";
export const GET_FEE_RATE_FAILURE = "GET_FEE_RATE_FAILURE";

export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";

export const SET_BATCH_TRANSACTION_COMMISSION_PERCENT =
  "SET_BATCH_TRANSACTION_COMMISSION_PERCENT";

export const CLEAR_BATCH_TRANSACTION_COMMISSION_PERCENT =
  "CLEAR_BATCH_TRANSACTION_COMMISSION_PERCENT";

export const SET_UPLOAD_PERCENT = "SET_UPLOAD_PERCENT";
export const CLEAR_UPLOAD_PERCENT = "CLEAR_UPLOAD_PERCENT";

export const SET_UPLOADED_SUCCESS = "SET_UPLOADED_SUCCESS";
export const SET_UPLOADED_FAILURE = "SET_UPLOADED_FAILURE";

export const SET_UPLOADING_TRUE = "SET_UPLOADING_TRUE";
export const SET_UPLOADING_FALSE = "SET_UPLOADING_FALSE";

export const SET_RECEIPT_DATA_SUCCESS = "SET_RECEIPT_DATA_SUCCESS";
export const SET_RECEIPT_DATA_FAILURE = "SET_RECEIPT_DATA_FAILURE";
