export const SET_LOADING_TRUE = "SET_LOADING_TRUE";

export const GET_FEE_RATE_SUCCESS = "GET_FEE_RATE_SUCCESS";
export const GET_FEE_RATE_FAILURE = "GET_FEE_RATE_FAILURE";

export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILURE = "GET_BALANCE_FAILURE";
