export const SET_LOADING_TRUE = "SET_LOADING_TRUE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

export const VALIDATE_PASSCODE_SUCCESS = "VALIDATE_PASSCODE_SUCCESS";
export const VALIDATE_PASSCODE_FAILURE = "VALIDATE_PASSCODE_FAILURE";

export const LOGOUT = "LOGOUT";
